### ISSUE TITLE
Experiment on SARCOS dataset

### ISSUE THREAD

**Issue by tuantran23012000** [AvivNavon/pareto-hypernetworks#2]
Can you provide the experiment on the SARCOS dataset?

**Comment by AvivNavon** [comment]
We've added code to reproduce the SARCOS experiment results: https://github.com/AvivNavon/pareto-hypernetworks/tree/master/experiments/sarcos

**Comment by tuantran23012000** [comment]
Thank you for sharing, I will close my issue.
