### ISSUE TITLE
How to cumpute Uniformity?

### ISSUE THREAD

**Issue by violet-sto** [AvivNavon/pareto-hypernetworks#4]
Excuse me, where is the code for computing uniformity?

**Comment by AvivNavon** [comment]
Hi, you can use something like the code snippet below following the definition in http://proceedings.mlr.press/v119/mahapatra20a.html: 

```python
def non_uniformity(losses, ray):
    m = len(losses)
    rl = losses * ray
    normalized_rl = rl / rl.sum()
    non_unif = (normalized_rl * torch.log(normalized_rl * m)).sum()

    return non_unif
```

**Comment by violet-sto** [comment]
Thank you, this code is easy to understand.

**Comment by AvivNavon** [comment]
Great, closing the issue.
