### ISSUE TITLE
How to get the reported performance

### ISSUE THREAD

**Issue by violet-sto** [AvivNavon/pareto-hypernetworks#5]
I have some trouble evaluating the performance. Take experiments about image classification as an example, 

1) Does the reported uniformity stand for the mean of uniformity computed per preference ray, but the std is not shown?
2) In Appendix A, PHN is evaluated over 25 rays, does it mean that the hyperparameters of PHN is determined w.r.t the HV over 25 points, while the HV reported in Table 1 is computed over the same 5 rays as baselines.

**Comment by AvivNavon** [comment]
Hi, 
1. Yes, we report the mean of uniformity.
2. No, in Table 1 we report the HV for PHN evaluated over 25 evenly spaced rays (using a single PHN model compared to 5 baseline models). We report the HV corresponds to the 5 baseline rays in Appendix B.4, Table 6.
