### ISSUE TITLE
In figure1, algorithm NSGA-III, how to get the relationship between the preference rays and solutions?

### ISSUE THREAD

**Issue by jhrsya** [AvivNavon/pareto-hypernetworks#6]
In the algorithm NSGA-III, the population size(the number of solutions) is larger or equal than the the number of preference rays. I use the python package pymoo to implement the algorithm NSAG-III, but I don't know which population member(the solution) corresponds to which preference rays. Thankyou for your help.

**Comment by AvivNavon** [comment]
Hi @jhrsya 
IIRC, when providing `n` `ref_dirs` you will get the same number of solutions as outputs (unless the `pymoo` API has changed).

**Comment by jhrsya** [comment]
Get it, thankyou!
