### ISSUE TITLE
Can this method scale up to Transformer based models such as ViT and GPT-2 with hundreds of millions of parameters?

### ISSUE THREAD

**Issue by tanganke** [AvivNavon/pareto-hypernetworks#9]
Thank you for the great work. 

I am wondering if it is possible to scale up this method to transformer-based models such as ViT and GPT-2 with hundreds of millions of parameters? Are there any methods for Pareto set learning that can be applied to large models now? 

I am new to the Pareto set learning field, and I would greatly appreciate your time to answer these questions.

**Comment by AvivNavon** [comment]
Hi @tanganke.
Generally, I see two ways of scaling to larger models:
- One is to keep outputting the entire set of parameters but with a more parameter-efficient approach like chunking (see example in Section 7 of our paper https://arxiv.org/pdf/2010.04104.pdf).
- A possibly better and more scalable approach is to use the hypernet for outputting only a subset of the parameters of the target model (and share the rest of the parameters between different preference vectors).

Hope that helps

**Comment by tanganke** [comment]
Thank you for your quick response!

However, it still looks like an open question to learn the entire Pareto front for models with hundreds of millions of parameters in a consumer GPU such as 3090 with 24G memory.

**Comment by AvivNavon** [comment]
I'm not familiar with a lot of works that explore these ideas for large models. There is this one paper which consider LLMs: https://arxiv.org/pdf/2402.02030.pdf

**Comment by tanganke** [comment]
Yes. This helps me a lot.
